# Generated by Django 3.0 on 2020-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childreg',
            name='id',
        ),
        migrations.AlterField(
            model_name='childreg',
            name='child_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
